security:
    providers:
        my_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: <%= @ldap_base_dn %>
                search_dn: <%= @ldap_search_dn %>
                search_password: <%= @ldap_search_pw %>
                default_roles: ROLE_USER
                uid_key: uid
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            http_basic_ldap:
                service: Symfony\Component\Ldap\Ldap
                dn_string: <%= @ldap_dn_string %>
                query_string: <%= @ldap_query_string %>

    access_control:
        - { path: ^/, roles: ROLE_USER }
